"""Publish the research write-ups as real, crawlable HTML pages under /research.

Why this exists
---------------
The out-of-sample validation reports were only ever Markdown files inside the
engine repository. They are the most substantive, most defensible content the
project has - the only pages that document *how* the modulator was tested rather
than asserting that it works - and none of it was reachable from the web. That
is content a search engine cannot rank and a reader cannot check.

Rather than hand-transcribing tables of 20 baskets into HTML (where a single
mistyped digit turns published evidence into a false claim), this script reads
the Markdown verbatim from _research/ and renders it. The numbers on the site
are therefore the numbers in the source, by construction.

_research/ is the Jekyll-excluded source directory, same convention as _src/:
the Markdown never gets served, only the generated pages under research/.

Refreshing the content: re-copy the Markdown from the engine repo into
_research/ and re-run this script. Do not edit research/*.html by hand.

Usage
-----
    python tools/build_research.py            # write research/*.html
    python tools/build_research.py --check    # verify only, exit 1 if stale
"""
import html as htmllib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "_research"
OUT_DIR = ROOT / "research"

BANNER = ("<!-- GENERATED by tools/build_research.py from _research/*.md "
          "- DO NOT EDIT, your changes will be overwritten -->\n")

SITE = "https://aqmath.xyz"

# Markdown link/image targets are repo-relative. Map them onto public URLs.
REWRITE = {
    "oos_assets/": "/research/assets/",
    "OOS_V14_NEW_TOKENS_RESULTS.md": "/research/oos-v14-new-tokens",
    "OOS_V14_NEW_TOKENS_RESULTS.zh-CN.md": "/research/oos-v14-new-tokens-zh",
}

# Shown above every table and chart on these pages, for the same reason it is
# shown on /results and /backtest: a performance figure has to carry its
# qualifier where it is read, not in the footer.
SIM_NOTICE = {
    "en": ("<strong>Simulated results &mdash; no real money.</strong> Every figure below is "
           "computed from historical price data by a backtest. No capital was invested and no "
           "orders were placed. Backtests apply a strategy to the past with full knowledge of how "
           "that period turned out, and the figures exclude slippage and liquidity effects, though a "
           "simulated 0.1% exchange fee is charged on every rebalance, DCA buy and redeployment. "
           "Simulated and past performance is <strong>not a reliable indicator of future "
           "results</strong>. AQMath is software, not investment advice."),
    "zh-Hans": ("<strong>模拟结果 &mdash; 未使用真实资金。</strong>以下每一项数据均由回测根据历史价格数据计算得出。"
                "未投入任何资金，也未下过任何订单。回测是在完全知晓该时段结果的前提下把策略套用于过去，"
                "且数据不包含滑点与流动性影响，但会对每次再平衡、DCA 买入和资金重新部署收取 0.1% 的模拟交易所手续费。"
                "模拟表现与过往表现<strong>不能可靠地预示未来结果</strong>。"
                "AQMath 是软件，不是投资建议。"),
}

UI = {
    "en": {
        "hubTitle": "Research &amp; Validation",
        "hubKicker": "Out-of-sample evidence",
        "hubIntro": ("Published test reports for the AQMath Deleverage Modulator. Each report is "
                     "generated verbatim from the source write-up in the engine repository, so the "
                     "figures here are the figures the test produced. The point of publishing them "
                     "is that a drawdown claim is only worth as much as the test behind it."),
        "backToHub": "&larr; All research",
        "alsoIn": "Also available in",
        "published": "Published",
    },
    "zh-Hans": {
        "hubTitle": "研究与验证",
        "hubKicker": "样本外证据",
        "hubIntro": "AQMath 去杠杆调节器的公开测试报告。",
        "backToHub": "&larr; 全部研究",
        "alsoIn": "其他语言版本",
        "published": "发布日期",
    },
}

DOCS = [
    {
        "src": "oos-v14-new-tokens.md",
        "out": "oos-v14-new-tokens.html",
        "path": "/research/oos-v14-new-tokens",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-07-17",
        "title": "Out-of-Sample Validation: Deleverage Modulator v14.0 on an Unseen Token Universe",
        "shortTitle": "OOS Validation &mdash; v14.0 on Unseen Tokens",
        "description": ("Out-of-sample test of the shipped AQMath Deleverage Modulator v14.0 on 16 "
                        "baskets of tokens never used for tuning: median 54.3 pp drawdown "
                        "reduction, Calmar improved in 16/16, plus dead-token and short-history "
                        "stress cases."),
        "altLabel": "\u4e2d\u6587",
    },
    {
        "src": "oos-v14-new-tokens.zh-CN.md",
        "out": "oos-v14-new-tokens-zh.html",
        "path": "/research/oos-v14-new-tokens-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-07-17",
        "title": "\u6837\u672c\u5916\u9a8c\u8bc1\uff1a\u53bb\u6760\u6746\u8c03\u8282\u5668 v14.0 \u5728\u672a\u89c1\u8fc7\u7684\u4ee3\u5e01\u7ec4\u5408\u4e0a\u7684\u8868\u73b0",
        "shortTitle": "\u6837\u672c\u5916\u9a8c\u8bc1 &mdash; v14.0 \u672a\u89c1\u4ee3\u5e01",
        "description": ("AQMath \u53bb\u6760\u6746\u8c03\u8282\u5668 v14.0 \u7684\u6837\u672c\u5916\u6d4b\u8bd5\uff1a"
                        "16 \u4e2a\u4ece\u672a\u7528\u4e8e\u8c03\u53c2\u7684\u4ee3\u5e01\u7ec4\u5408\uff0c"
                        "\u6700\u5927\u56de\u6492\u4e2d\u4f4d\u6570\u524a\u51cf 54.3 \u4e2a\u767e\u5206\u70b9\uff0c"
                        "Calmar \u5728 16/16 \u4e2a\u7ec4\u5408\u4e2d\u63d0\u5347\u3002"),
        "altLabel": "English",
    },
]

# Language pairs that describe the same document, for hreflang.
TRANSLATION_SETS = [["/research/oos-v14-new-tokens", "/research/oos-v14-new-tokens-zh"]]


# ---------------------------------------------------------------- markdown ---

CODE_RE = re.compile(r"`([^`]+)`")
IMG_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
BOLD_RE = re.compile(r"\*\*(.+?)\*\*")
ITALIC_RE = re.compile(r"\*([^*]+)\*")
TABLE_RULE_RE = re.compile(r"^\|[\s:|-]+\|$")


def rewrite_target(target):
    for old, new in REWRITE.items():
        if target.startswith(old):
            return new + target[len(old):]
        if target == old:
            return new
    return target


def svg_box(url):
    """Intrinsic width/height so the chart does not shift the page while loading."""
    path = ROOT / url.lstrip("/")
    if not path.exists():
        raise SystemExit(f"referenced asset missing: {url}")
    head = path.read_text(encoding="utf-8")[:400]
    w = re.search(r'\bwidth="(\d+)"', head)
    h = re.search(r'\bheight="(\d+)"', head)
    if not (w and h):
        raise SystemExit(f"cannot read intrinsic size of {url}")
    return w.group(1), h.group(1)


def inline(text):
    """Inline Markdown -> HTML. Escapes first, so source text can never inject markup."""
    codes = []

    def stash(m):
        codes.append(htmllib.escape(m.group(1)))
        return f"\x00{len(codes) - 1}\x00"

    text = CODE_RE.sub(stash, text)
    text = htmllib.escape(text)
    text = BOLD_RE.sub(r"<strong>\1</strong>", text)
    text = ITALIC_RE.sub(r"<em>\1</em>", text)
    text = LINK_RE.sub(
        lambda m: f'<a href="{rewrite_target(m.group(2))}">{m.group(1)}</a>', text)
    text = re.sub(r"\x00(\d+)\x00", lambda m: f"<code>{codes[int(m.group(1))]}</code>", text)
    return text


def render_table(rows):
    align_row = rows[1]
    aligns = []
    for cell in [c.strip() for c in align_row.strip("|").split("|")]:
        if cell.endswith(":") and cell.startswith(":"):
            aligns.append("center")
        elif cell.endswith(":"):
            aligns.append("right")
        else:
            aligns.append("left")

    def cells(row):
        return [c.strip() for c in row.strip().strip("|").split("|")]

    out = ['<div class="rs-tablewrap">', "<table>", "<thead><tr>"]
    for i, cell in enumerate(cells(rows[0])):
        a = aligns[i] if i < len(aligns) else "left"
        out.append(f'<th style="text-align:{a}">{inline(cell)}</th>')
    out.append("</tr></thead>")
    out.append("<tbody>")
    for row in rows[2:]:
        out.append("<tr>")
        for i, cell in enumerate(cells(row)):
            a = aligns[i] if i < len(aligns) else "left"
            out.append(f'<td style="text-align:{a}">{inline(cell)}</td>')
        out.append("</tr>")
    out.append("</tbody></table></div>")
    return "\n".join(out)


def render_paragraph(lines):
    if len(lines) > 1 and all(l.startswith("**") for l in lines):
        # A metadata block (Date:/Engine:/Status:) - one fact per line, as written.
        return "<p>" + "<br>\n".join(inline(l) for l in lines) + "</p>"
    return "<p>" + inline(" ".join(lines)) + "</p>"


def markdown_to_html(md):
    """Render the Markdown subset these reports actually use. Not a general parser:
    it fails loudly on anything it does not recognise rather than dropping it."""
    lines = md.replace("\r\n", "\n").split("\n")
    out = []
    para = []
    items = []
    i = 0

    def flush():
        if para:
            out.append(render_paragraph(list(para)))
            para.clear()
        if items:
            out.append("<ul>" + "".join(f"<li>{inline(x)}</li>" for x in items) + "</ul>")
            items.clear()

    while i < len(lines):
        raw = lines[i]
        line = raw.strip()

        if not line:
            flush()
            i += 1
            continue

        if line == "---":
            flush()
            out.append("<hr>")
            i += 1
            continue

        m = re.match(r"^(#{1,4})\s+(.*)$", line)
        if m:
            flush()
            lvl = len(m.group(1))
            out.append(f"<h{lvl}>{inline(m.group(2))}</h{lvl}>")
            i += 1
            continue

        if line.startswith("> "):
            flush()
            out.append(f"<blockquote>{inline(line[2:])}</blockquote>")
            i += 1
            continue

        m = IMG_RE.fullmatch(line)
        if m:
            flush()
            url = rewrite_target(m.group(2))
            w, h = svg_box(url)
            out.append(f'<figure class="rs-fig"><img src="{url}" alt="{htmllib.escape(m.group(1))}" '
                       f'width="{w}" height="{h}" loading="lazy" decoding="async"></figure>')
            i += 1
            continue

        if line.startswith("|"):
            flush()
            if i + 1 >= len(lines) or not TABLE_RULE_RE.match(lines[i + 1].strip()):
                raise SystemExit(f"table without an alignment row at line {i + 1}: {line}")
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append(lines[i].strip())
                i += 1
            out.append(render_table(rows))
            continue

        if line.startswith("- "):
            if para:
                flush()
            items.append(line[2:])
            i += 1
            continue

        if items and raw.startswith("  "):
            # Continuation of the previous list item.
            items[-1] = items[-1] + " " + line
            i += 1
            continue

        para.append(line)
        i += 1

    flush()
    return "\n".join(out)


# ------------------------------------------------------------------- pages ---

def asset_stamp():
    """Reuse whatever stamp tools/stamp_version.py last wrote, so these pages
    never point at a stylesheet version that does not exist."""
    body = (ROOT / "terms.html").read_text(encoding="utf-8")
    m = re.search(r'href="/styles\.min\.css\?v=([\w]+)"', body)
    if not m:
        raise SystemExit("cannot read current asset stamp from terms.html")
    return m.group(1)


def alternates(path):
    links = []
    for group in TRANSLATION_SETS:
        if path not in group:
            continue
        for other in group:
            doc = next(d for d in DOCS if d["path"] == other)
            links.append(f'<link rel="alternate" hreflang="{doc["lang"]}" '
                         f'href="{SITE}{other}">')
        links.append(f'<link rel="alternate" hreflang="x-default" href="{SITE}{group[0]}">')
    return links


def shell(lang, html_lang, title, description, path, body, extra_head=()):
    stamp = asset_stamp()
    head = "\n".join(list(extra_head) + alternates(path))
    return BANNER + f"""<!DOCTYPE html>
<html lang="{html_lang}">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<meta name="description" content="{description}">
<meta name="robots" content="index, follow">
<link rel="canonical" href="{SITE}{path}">
<link rel="icon" href="/favicon.ico">
<link rel="icon" type="image/png" sizes="512x512" href="/favicon.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<meta property="og:type" content="article">
<meta property="og:url" content="{SITE}{path}">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:site_name" content="AQMath">
{head}
<!-- Fonts are self-hosted (see @font-face in styles.css) so no request reaches Google. -->
<link rel="preload" href="/fonts/plus-jakarta-sans-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="/styles.min.css?v={stamp}">
</head>
<body>

<main class="legal-page research-page">
    <a class="legal-page-brand" href="/">
        <div class="logo-box">AQ</div>
        <div>
            <div class="logo-name">AQMath</div>
            <div class="logo-tag">&larr; aqmath.xyz</div>
        </div>
    </a>

{body}
</main>

<footer class="site-footer">
    &copy; 2026 AQMath &mdash; Private. Non-Custodial.<br>
    <a href="/">Home</a><span class="sep">|</span><a href="/about">About</a><span class="sep">|</span><a href="/research">Research</a><span class="sep">|</span><a href="/impressum">Impressum</a><span class="sep">|</span><a href="/privacy">Privacy</a><span class="sep">|</span><a href="/terms">Terms</a><span class="sep">|</span><a href="/widerruf">Widerruf</a>
</footer>

</body>
</html>
"""


def render_doc(doc):
    md = (SRC_DIR / doc["src"]).read_text(encoding="utf-8")
    ui = UI[doc["lang"]]
    other = next((d for d in DOCS
                  for g in TRANSLATION_SETS
                  if doc["path"] in g and d["path"] in g and d["path"] != doc["path"]), None)

    body_md = markdown_to_html(md)
    # The source's own cross-language line points at a repo file; the header link
    # below is the real one, so drop the duplicate.
    body_md = re.sub(r"<blockquote>.*?</blockquote>\s*", "", body_md, count=1, flags=re.S)

    nav = [f'<p class="rs-nav"><a href="/research">{ui["backToHub"]}</a>']
    if other:
        nav.append(f'<span class="sep">|</span>{ui["alsoIn"]} '
                   f'<a href="{other["path"]}" hreflang="{other["lang"]}">{doc["altLabel"]}</a>')
    nav.append("</p>")

    # The document title has to be the first heading a reader and a crawler meet,
    # so lift it out of the rendered body and put the notices underneath it.
    m = re.match(r"\s*(<h1>.*?</h1>)\s*", body_md, flags=re.S)
    if not m:
        raise SystemExit(f"{doc['src']}: expected the document to open with a level-1 heading")
    heading, rest = m.group(1), body_md[m.end():]

    body = "\n".join([
        "".join(nav),
        heading,
        f'<p class="legal-updated">{ui["published"]}: {doc["published"]}</p>',
        f'<p class="sim-notice">{SIM_NOTICE[doc["lang"]]}</p>',
        rest,
    ])
    return shell(doc["lang"], doc["htmlLang"], doc["title"], doc["description"],
                 doc["path"], body)


def render_hub():
    ui = UI["en"]
    cards = []
    for doc in DOCS:
        if doc["lang"] != "en":
            continue
        other = next((d for d in DOCS
                      for g in TRANSLATION_SETS
                      if doc["path"] in g and d["path"] in g and d["path"] != doc["path"]), None)
        alt = (f' <span class="rs-card-alt">&middot; <a href="{other["path"]}" '
               f'hreflang="{other["lang"]}">{doc["altLabel"]}</a></span>') if other else ""
        cards.append(
            f'<li class="rs-card"><a href="{doc["path"]}">{doc["shortTitle"]}</a>'
            f'<span class="rs-card-date">{doc["published"]}</span>{alt}'
            f'<p>{doc["description"]}</p></li>')
    body = "\n".join([
        f'<div class="rs-kicker">{ui["hubKicker"]}</div>',
        f'<h1>{ui["hubTitle"]}</h1>',
        f'<p>{ui["hubIntro"]}</p>',
        '<ul class="rs-list">',
        *cards,
        "</ul>",
        '<p>Interactive version: run the same engine on your own price data at '
        '<a href="/backtest">/backtest</a>, or see the live paper-trading log at '
        '<a href="/results">/results</a>.</p>',
    ])
    return shell(
        "en", "en", "Research &amp; Validation &mdash; AQMath",
        "Published out-of-sample validation reports for the AQMath Deleverage Modulator: "
        "test methodology, per-basket results, stress cases and caveats.",
        "/research", body)


def build():
    pages = {"index.html": render_hub()}
    for doc in DOCS:
        pages[doc["out"]] = render_doc(doc)
    return pages


def main(check_only=False):
    if not SRC_DIR.exists():
        raise SystemExit(f"missing source directory: {SRC_DIR}")
    pages = build()

    stale = []
    for name, text in pages.items():
        path = OUT_DIR / name
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            stale.append(name)

    if check_only:
        if stale:
            print("research pages STALE - re-run tools/build_research.py:")
            for n in stale:
                print("  research/" + n)
            return 1
        print(f"research pages OK - {len(pages)} in sync with _research/")
        return 0

    OUT_DIR.mkdir(exist_ok=True)
    for name, text in pages.items():
        (OUT_DIR / name).write_text(text, encoding="utf-8")
        h1 = len(re.findall(r"<h1\b", text))
        if h1 != 1:
            raise SystemExit(f"research/{name}: expected exactly 1 <h1>, found {h1}")
        print(f"  research/{name:28s} {len(text):>7,}B h1=1")
    print(f"wrote {len(pages)} research pages from {SRC_DIR.name}/")
    return 0


if __name__ == "__main__":
    sys.exit(main(check_only="--check" in sys.argv))
