"""Generate the five per-route HTML entry pages from _src/index.html.

Why the source moved out of the repo root
-----------------------------------------
_src/index.html is the single multi-view SPA document humans edit. Every file
in the site root that this script writes is a build artifact.

The reason for the split is a real indexing failure, not tidiness. This script
used to copy the whole source and patch only <head>, so /, /app, /docs,
/backtest and /results all shipped the *same* 311 KB body - byte-for-byte
identical, differing only in a title tag. Search engines treat that as one page
duplicated five times and index at most one of them. Unique titles do not fix
duplicate bodies.

So each generated page now keeps ONLY its own view container and drops the other
four. The CSS-class router (body.route-*) still works, because each page sets
its own class and only ever needs the view it ships. Cross-route <a href="/..">
links fall through to a normal navigation - app.js checks that a route's view
exists in the current document before handling the click in-page.

Jekyll (active: there is no .nojekyll) excludes _-prefixed directories from the
published site, so _src/ is never served. robots.txt disallows it as well, in
case Jekyll is ever turned off.

Pipeline order
--------------
    python tools/minify_css.py
    python tools/stamp_version.py
    python tools/build_pages.py

Usage:  python tools/build_pages.py [--check]
        --check verifies the committed artifacts match the source and exits 1
        if they are stale, without writing anything.
"""
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "_src" / "index.html"

BANNER = ("<!-- GENERATED by tools/build_pages.py from _src/index.html "
          "- DO NOT EDIT, your changes will be overwritten -->\n")

# One entry per route. `view` is the id of the only view container the page
# keeps; every other view is stripped out.
PAGES = {
    "index.html": {
        "path": "/",
        "view": "landingView",
        "robots": "index, follow",
        "title": "AQMath — Crypto Portfolio Rebalancer | Risk Parity",
        "description": "Non-custodial crypto portfolio rebalancer with Risk Parity math and Deleverage Shield crash protection. Private — no wallet connection, no account needed.",
    },
    "docs.html": {
        "path": "/docs",
        "view": "docView",
        "robots": "index, follow",
        "title": "System Documentation — AQMath",
        "description": "Full technical documentation of AQMath: Risk Parity engine, Deleverage Shield, DCA safety pipeline and the non-custodial privacy architecture.",
    },
    "backtest.html": {
        "path": "/backtest",
        "view": "backtestView",
        "robots": "index, follow",
        "title": "Backtest — AQMath Deleverage Shield",
        "description": "Interactive 8.7-year walk-forward backtest of the AQMath Deleverage Shield — compare drawdowns and returns against plain Buy & Hold.",
    },
    "results.html": {
        "path": "/results",
        "view": "resultsView",
        "robots": "index, follow",
        "title": "New-Token Stress Test — AQMath",
        "description": "Out-of-sample stress test of the AQMath Shield on 182 fresh coin baskets — including tokens never used to build or tune the model.",
    },
    # The app is a paid, closed tool behind a beta key: there is no public
    # content to rank, and leaving it indexable only added a fifth duplicate.
    "app.html": {
        "path": "/app",
        "view": "appView",
        "robots": "noindex, follow",
        "title": "App — AQMath Portfolio Rebalancer",
        "description": "The AQMath app: track your portfolio, distribute DCA and optimize with Risk Parity math — non-custodial, private, no account needed.",
    },
}

ALL_VIEWS = [meta["view"] for meta in PAGES.values()]
VIEW_OPEN = re.compile(r'<div id="(' + "|".join(ALL_VIEWS) + r')"')
DIV_CLOSE = re.compile(r"</div\s*>")


def view_spans(lines):
    """Map each view id to the inclusive (start, end) line span of its <div>.

    Depth is tracked by counting <div ... > against </div>. That is only safe
    because the source has no inline <script> blocks and no '<div' inside any
    quoted attribute or string - both verified before this approach was chosen.
    """
    spans = {}
    i = 0
    while i < len(lines):
        m = VIEW_OPEN.search(lines[i])
        if not m:
            i += 1
            continue
        vid = m.group(1)
        if vid in spans:
            raise SystemExit(f"duplicate view container id in source: {vid}")
        depth = 0
        end = None
        for j in range(i, len(lines)):
            depth += lines[j].count("<div") - len(DIV_CLOSE.findall(lines[j]))
            if depth <= 0:
                end = j
                break
        if end is None:
            raise SystemExit(f"unbalanced <div> nesting inside #{vid}")
        spans[vid] = (i, end)
        i = end + 1

    missing = [v for v in ALL_VIEWS if v not in spans]
    if missing:
        raise SystemExit(f"view container(s) not found in source: {missing}")
    return spans


def strip_other_views(src, keep):
    lines = src.split("\n")
    spans = view_spans(lines)
    # Drop from the bottom up so earlier spans keep their indices.
    for vid, (start, end) in sorted(spans.items(), key=lambda kv: -kv[1][0]):
        if vid == keep:
            continue
        lines[start:end + 1] = [
            f"<!-- #{vid} omitted: this entry page ships only #{keep} -->"
        ]
    return "\n".join(lines)


def patch(html, pattern, replacement, name):
    out, n = re.subn(pattern, replacement, html, count=1)
    if n != 1:
        raise SystemExit(f"pattern not found while building {name}: {pattern}")
    return out


def render(src, name, meta):
    url = "https://aqmath.xyz" + meta["path"]
    html = strip_other_views(src, meta["view"])
    html = patch(html, r"<title>.*?</title>", f"<title>{meta['title']}</title>", name)
    html = patch(html, r'(<meta name="description" content=")[^"]*(">)',
                 rf"\g<1>{meta['description']}\g<2>", name)
    html = patch(html, r'(<meta name="robots" content=")[^"]*(">)',
                 rf"\g<1>{meta['robots']}\g<2>", name)
    html = patch(html, r'(<link rel="canonical" href=")[^"]*(">)', rf"\g<1>{url}\g<2>", name)
    html = patch(html, r'(<meta property="og:url" content=")[^"]*(">)', rf"\g<1>{url}\g<2>", name)
    # The source's og/twitter copy is written for the landing page, so only the
    # sub-pages get theirs rewritten - otherwise / would lose its social blurb.
    if meta["path"] != "/":
        for attr, value in (("property=\"og:title\"", meta["title"]),
                           ("property=\"og:description\"", meta["description"]),
                           ("name=\"twitter:title\"", meta["title"]),
                           ("name=\"twitter:description\"", meta["description"])):
            html = patch(html, r'(<meta ' + attr + r' content=")[^"]*(">)',
                         rf"\g<1>{value}\g<2>", name)
    return BANNER + html


def body_digest(html):
    """md5 + length of <body>, i.e. exactly what a crawler compares."""
    m = re.search(r"<body[^>]*>(.*)</body>", html, re.S)
    if not m:
        raise SystemExit("no <body> found in generated page")
    body = m.group(1).encode("utf-8")
    return hashlib.md5(body).hexdigest()[:10], len(body)


COMMENT_RE = re.compile(r"<!--.*?-->", re.S)


def verify(pages):
    """Guard the exact regressions that let the duplicate-body bug ship."""
    seen = {}
    for name, html in pages.items():
        h1s = re.findall(r"<h1\b", COMMENT_RE.sub("", html))
        if len(h1s) != 1:
            raise SystemExit(f"{name}: expected exactly 1 <h1>, found {len(h1s)}")
        digest, size = body_digest(html)
        if digest in seen:
            raise SystemExit(
                f"{name} has a byte-identical body to {seen[digest]} - "
                "duplicate content, search engines will index only one"
            )
        seen[digest] = name
        print(f"  {name:16s} {PAGES[name]['path']:10s} body={size:>7,}B "
              f"md5={digest} robots={PAGES[name]['robots']} h1=1")


def build(check_only=False):
    if not SRC.exists():
        raise SystemExit(f"source missing: {SRC.relative_to(ROOT)}")
    src = SRC.read_text(encoding="utf-8")
    pages = {name: render(src, name, meta) for name, meta in PAGES.items()}

    print(f"built from {SRC.relative_to(ROOT)} ({len(src):,} chars)")
    verify(pages)

    if check_only:
        stale = [n for n, html in pages.items()
                 if not (ROOT / n).exists()
                 or (ROOT / n).read_text(encoding="utf-8") != html]
        if stale:
            print(f"STALE, re-run without --check: {', '.join(sorted(stale))}")
            return 1
        print("all entry pages current")
        return 0

    for name, html in pages.items():
        (ROOT / name).write_text(html, encoding="utf-8")
    print(f"wrote {len(pages)} entry pages")
    return 0


if __name__ == "__main__":
    sys.exit(build(check_only="--check" in sys.argv))
