"""Generate the five per-route HTML entry pages from _src/index.html.

Why the source moved out of the repo root
-----------------------------------------
_src/index.html is the single multi-view SPA document humans edit. Every file
in the site root that this script writes is a build artifact.

The reason for the split is a real indexing failure, not tidiness. This script
used to copy the whole source and patch only <head>, so /, /app, /docs,
/backtest and /results all shipped the *same* 311 KB body - byte-for-byte
identical, differing only in a title tag. Search engines treat that as one page
duplicated five times and index at most one of them. Unique titles do not fix
duplicate bodies.

So each generated page now keeps ONLY its own view container and drops the other
four. The CSS-class router (body.route-*) still works, because each page sets
its own class and only ever needs the view it ships. Cross-route <a href="/..">
links fall through to a normal navigation - app.js checks that a route's view
exists in the current document before handling the click in-page.

Jekyll (active: there is no .nojekyll) excludes _-prefixed directories from the
published site, so _src/ is never served. robots.txt disallows it as well, in
case Jekyll is ever turned off.

Pipeline order
--------------
    python tools/minify_css.py
    python tools/stamp_version.py
    python tools/build_pages.py

Usage:  python tools/build_pages.py [--check]
        --check verifies the committed artifacts match the source and exits 1
        if they are stale, without writing anything.
"""
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "_src" / "index.html"

BANNER = ("<!-- GENERATED by tools/build_pages.py from _src/index.html "
          "- DO NOT EDIT, your changes will be overwritten -->\n")

# One entry per route. `view` is the id of the only view container the page
# keeps; every other view is stripped out.
PAGES = {
    "index.html": {
        "path": "/",
        "view": "landingView",
        "robots": "index, follow",
        "title": "AQMath \u2014 Crypto Portfolio Rebalancer | Risk Parity",
        "description": "Non-custodial crypto portfolio rebalancer with Risk Parity math and Deleverage Shield crash protection. Private \u2014 no wallet connection, no account needed.",
    },
    "docs.html": {
        "path": "/docs",
        "view": "docView",
        "robots": "index, follow",
        "title": "System Documentation \u2014 AQMath",
        "description": "Full technical documentation of AQMath: Risk Parity engine, Deleverage Shield, DCA safety pipeline and the non-custodial privacy architecture.",
    },
    "backtest.html": {
        "path": "/backtest",
        "view": "backtestView",
        "robots": "index, follow",
        "title": "Backtest \u2014 AQMath Deleverage Shield",
        "description": "Interactive 8.7-year walk-forward backtest of the AQMath Deleverage Shield \u2014 compare drawdowns and returns against plain Buy & Hold.",
    },
    "results.html": {
        "path": "/results",
        "view": "resultsView",
        "robots": "index, follow",
        "title": "New-Token Stress Test \u2014 AQMath",
        "description": "Out-of-sample stress test of the AQMath Shield on 182 fresh coin baskets \u2014 including tokens never used to build or tune the model.",
    },
    # The app is a paid, closed tool behind a beta key: there is no public
    # content to rank, and leaving it indexable only added a fifth duplicate.
    "app.html": {
        "path": "/app",
        "view": "appView",
        "robots": "noindex, follow",
        "title": "App \u2014 AQMath Portfolio Rebalancer",
        "description": "The AQMath app: track your portfolio, distribute DCA and optimize with Risk Parity math \u2014 non-custodial, private, no account needed.",
    },
}

# ---------------------------------------------------------------- JSON-LD ---
# Per-page structured data. The source (_src/index.html) ships a baseline
# WebApplication block; render() replaces it with the page-specific graph.

_SITE = "https://aqmath.xyz"
_PERSON = {"@id": f"{_SITE}/#momir-demirov"}
_ORG = {
    "@type": "Organization",
    "@id": f"{_SITE}/#organization",
    "name": "AQMath",
    "url": _SITE,
    "logo": f"{_SITE}/favicon.png",
    "description": "Quantitative, non-custodial crypto portfolio rebalancer with KKT Risk-Parity weighting and Deleverage Modulator drawdown protection.",
    "sameAs": [
        "https://x.com/aqmathapp",
        "https://t.me/DoNotAskMex",
        "https://www.reddit.com/user/weaforex/",
        "https://substack.com/@aqmathxyz",
    ],
}
_WEBAPP = {
    "@type": "WebApplication",
    "name": "AQMath",
    "url": _SITE,
    "description": "Quantitative crypto portfolio rebalancer with Deleverage Modulator drawdown protection. Risk Parity mathematics, DCA optimization, and automatic de-risking during market crashes.",
    "applicationCategory": "FinanceApplication",
    "operatingSystem": "Any",
    "offers": [
        {"@type": "Offer", "name": "Beta Access", "price": "0", "priceCurrency": "USD",
         "description": "Limited slots, access review required"},
        {"@type": "Offer", "name": "Black Annual Access", "price": "999", "priceCurrency": "EUR",
         "description": "Annual subscription \u2014 \u20ac999/year, paid in USDC or EURC"},
    ],
    "featureList": [
        "Risk Parity Optimization",
        "Deleverage Modulator Drawdown Protection",
        "DCA Distribution",
        "Non-Custodial Privacy",
        "Continuous Auto De-Risk",
    ],
    "creator": _PERSON,
}

# Regex to extract FAQ Q&A pairs from the landing-page HTML.
_FAQ_RE = re.compile(
    r'<div class="lp-faq-q"[^>]*>([^<]+)</div>\s*'
    r'<div class="lp-faq-a"[^>]*>(.*?)</div>',
    re.S)


def _extract_faq_schema(html):
    """Build a FAQPage JSON-LD object from the landing-page FAQ markup."""
    items = []
    for q, a in _FAQ_RE.findall(html):
        items.append({
            "@type": "Question",
            "name": q.strip(),
            "acceptedAnswer": {"@type": "Answer", "text": a.strip()},
        })
    if not items:
        return None
    return {"@context": "https://schema.org", "@type": "FAQPage",
            "itemListElement": items}


def _breadcrumb(label, path):
    items = [{"@type": "ListItem", "position": 1, "name": "Home", "item": _SITE + "/"}]
    items.append({"@type": "ListItem", "position": 2, "name": label, "item": _SITE + path})
    return {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": items}


PAGE_JSONLD = {
    "index.html": lambda: {
        "@context": "https://schema.org",
        "@graph": [
            {**_WEBAPP, "creator": _PERSON},
            _ORG,
        ],
    },
    "docs.html": lambda: {
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "TechArticle",
             "name": "AQMath System Documentation",
             "url": _SITE + "/docs",
             "description": "Full technical documentation of AQMath: Risk Parity engine, Deleverage Shield, DCA safety pipeline and the non-custodial privacy architecture.",
             "articleSection": "Technical Documentation",
             "author": _PERSON,
             "publisher": {"@id": f"{_SITE}/#organization"}},
            _breadcrumb("Documentation", "/docs"),
        ],
    },
    "backtest.html": lambda: {
        "@context": "https://schema.org",
        "@graph": [
            {**_WEBAPP, "name": "AQMath Backtest",
             "url": _SITE + "/backtest",
             "description": "Interactive 8.7-year walk-forward backtest of the AQMath Deleverage Shield.",
             "creator": _PERSON},
            _breadcrumb("Backtest", "/backtest"),
        ],
    },
    "results.html": lambda: {
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "Article",
             "name": "New-Token Stress Test",
             "url": _SITE + "/results",
             "description": "Out-of-sample stress test of the AQMath Shield on 182 fresh coin baskets.",
             "articleSection": "Research Results",
             "author": _PERSON,
             "publisher": {"@id": f"{_SITE}/#organization"}},
            _breadcrumb("Results", "/results"),
        ],
    },
    # app.html is noindex; keep the baseline WebApplication only.
    "app.html": lambda: {"@context": "https://schema.org", **_WEBAPP},
}

ALL_VIEWS = [meta["view"] for meta in PAGES.values()]
VIEW_OPEN = re.compile(r'<div id="(' + "|".join(ALL_VIEWS) + r')"')
DIV_CLOSE = re.compile(r"</div\s*>")


def view_spans(lines):
    """Map each view id to the inclusive (start, end) line span of its <div>.

    Depth is tracked by counting <div ... > against </div>. That is only safe
    because the source has no inline <script> blocks and no '<div' inside any
    quoted attribute or string - both verified before this approach was chosen.
    """
    spans = {}
    i = 0
    while i < len(lines):
        m = VIEW_OPEN.search(lines[i])
        if not m:
            i += 1
            continue
        vid = m.group(1)
        if vid in spans:
            raise SystemExit(f"duplicate view container id in source: {vid}")
        depth = 0
        end = None
        for j in range(i, len(lines)):
            depth += lines[j].count("<div") - len(DIV_CLOSE.findall(lines[j]))
            if depth <= 0:
                end = j
                break
        if end is None:
            raise SystemExit(f"unbalanced <div> nesting inside #{vid}")
        spans[vid] = (i, end)
        i = end + 1

    missing = [v for v in ALL_VIEWS if v not in spans]
    if missing:
        raise SystemExit(f"view container(s) not found in source: {missing}")
    return spans


def strip_other_views(src, keep):
    lines = src.split("\n")
    spans = view_spans(lines)
    # Drop from the bottom up so earlier spans keep their indices.
    for vid, (start, end) in sorted(spans.items(), key=lambda kv: -kv[1][0]):
        if vid == keep:
            continue
        lines[start:end + 1] = [
            f"<!-- #{vid} omitted: this entry page ships only #{keep} -->"
        ]
    return "\n".join(lines)


def patch(html, pattern, replacement, name):
    out, n = re.subn(pattern, replacement, html, count=1)
    if n != 1:
        raise SystemExit(f"pattern not found while building {name}: {pattern}")
    return out


def render(src, name, meta):
    url = "https://aqmath.xyz" + meta["path"]
    html = strip_other_views(src, meta["view"])
    html = patch(html, r"<title>.*?</title>", f"<title>{meta['title']}</title>", name)
    html = patch(html, r'(<meta name="description" content=")[^"]*(">)',
                 rf"\g<1>{meta['description']}\g<2>", name)
    html = patch(html, r'(<meta name="robots" content=")[^"]*(">)',
                 rf"\g<1>{meta['robots']}\g<2>", name)
    html = patch(html, r'(<link rel="canonical" href=")[^"]*(">)', rf"\g<1>{url}\g<2>", name)
    html = patch(html, r'(<meta property="og:url" content=")[^"]*(">)', rf"\g<1>{url}\g<2>", name)
    # The source's og/twitter copy is written for the landing page, so only the
    # sub-pages get theirs rewritten - otherwise / would lose its social blurb.
    if meta["path"] != "/":
        for attr, value in (("property=\"og:title\"", meta["title"]),
                           ("property=\"og:description\"", meta["description"]),
                           ("name=\"twitter:title\"", meta["title"]),
                           ("name=\"twitter:description\"", meta["description"])):
            html = patch(html, r'(<meta ' + attr + r' content=")[^"]*(">)',
                         rf"\g<1>{value}\g<2>", name)
    # Replace the source's baseline JSON-LD with the page-specific graph.
    if name in PAGE_JSONLD:
        ld_json = json.dumps(PAGE_JSONLD[name](), ensure_ascii=False, separators=(",", ":"))
        html = re.sub(
            r'<script type="application/ld\+json">.*?</script>',
            f'<script type="application/ld+json">{ld_json}</script>',
            html, count=1, flags=re.S)
    # Inject FAQPage schema on the landing page.
    if meta["path"] == "/":
        faq_schema = _extract_faq_schema(html)
        if faq_schema:
            faq_json = json.dumps(faq_schema, ensure_ascii=False, separators=(",", ":"))
            html = html.replace(
                "</head>",
                f'<script type="application/ld+json">{faq_json}</script>\n</head>')
    return BANNER + html


def body_digest(html):
    """md5 + length of <body>, i.e. exactly what a crawler compares."""
    m = re.search(r"<body[^>]*>(.*)</body>", html, re.S)
    if not m:
        raise SystemExit("no <body> found in generated page")
    body = m.group(1).encode("utf-8")
    return hashlib.md5(body).hexdigest()[:10], len(body)


COMMENT_RE = re.compile(r"<!--.*?-->", re.S)


def verify(pages):
    """Guard the exact regressions that let the duplicate-body bug ship."""
    seen = {}
    for name, html in pages.items():
        h1s = re.findall(r"<h1\b", COMMENT_RE.sub("", html))
        if len(h1s) != 1:
            raise SystemExit(f"{name}: expected exactly 1 <h1>, found {len(h1s)}")
        digest, size = body_digest(html)
        if digest in seen:
            raise SystemExit(
                f"{name} has a byte-identical body to {seen[digest]} - "
                "duplicate content, search engines will index only one"
            )
        seen[digest] = name
        print(f"  {name:16s} {PAGES[name]['path']:10s} body={size:>7,}B "
              f"md5={digest} robots={PAGES[name]['robots']} h1=1")


def build(check_only=False):
    if not SRC.exists():
        raise SystemExit(f"source missing: {SRC.relative_to(ROOT)}")
    src = SRC.read_text(encoding="utf-8")
    pages = {name: render(src, name, meta) for name, meta in PAGES.items()}

    print(f"built from {SRC.relative_to(ROOT)} ({len(src):,} chars)")
    verify(pages)

    if check_only:
        stale = [n for n, html in pages.items()
                 if not (ROOT / n).exists()
                 or (ROOT / n).read_text(encoding="utf-8") != html]
        if stale:
            print(f"STALE, re-run without --check: {', '.join(sorted(stale))}")
            return 1
        print("all entry pages current")
        return 0

    for name, html in pages.items():
        (ROOT / name).write_text(html, encoding="utf-8")
    print(f"wrote {len(pages)} entry pages")
    return 0


if __name__ == "__main__":
    sys.exit(build(check_only="--check" in sys.argv))
