"""Publish the research write-ups as real, crawlable HTML pages under /research.

Why this exists
---------------
The out-of-sample validation reports were only ever Markdown files inside the
engine repository. They are the most substantive, most defensible content the
project has - the only pages that document *how* the modulator was tested rather
than asserting that it works - and none of it was reachable from the web. That
is content a search engine cannot rank and a reader cannot check.

Rather than hand-transcribing tables of 20 baskets into HTML (where a single
mistyped digit turns published evidence into a false claim), this script reads
the Markdown verbatim from _research/ and renders it. The numbers on the site
are therefore the numbers in the source, by construction.

_research/ is the Jekyll-excluded source directory, same convention as _src/:
the Markdown never gets served, only the generated pages under research/.

Refreshing the content: re-copy the Markdown from the engine repo into
_research/ and re-run this script. Do not edit research/*.html by hand.

Usage
-----
    python tools/build_research.py            # write research/*.html
    python tools/build_research.py --check    # verify only, exit 1 if stale
"""
import html as htmllib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "_research"
OUT_DIR = ROOT / "research"

BANNER = ("<!-- GENERATED by tools/build_research.py from _research/*.md "
          "- DO NOT EDIT, your changes will be overwritten -->\n")

SITE = "https://aqmath.xyz"

# social-preview.png carries a hand-set stamp on purpose: it is consumed by
# social-media scrapers rather than by the running app, so stamp_version.py
# deliberately leaves it alone and audit_pages.py excludes it from the
# single-asset-stamp check. Keep it in step with the entry pages.
SOCIAL_IMAGE = f"{SITE}/social-preview.png?v=20260721b"
SOCIAL_IMAGE_ALT = ("AQMath &mdash; Risk Parity crypto portfolio rebalancer with "
                    "Deleverage Shield")

# Markdown link/image targets are repo-relative. Map them onto public URLs.
REWRITE = {
    "oos_assets/": "/research/assets/",
    "OOS_V14_NEW_TOKENS_RESULTS.md": "/research/oos-v14-new-tokens",
    "OOS_V14_NEW_TOKENS_RESULTS.zh-CN.md": "/research/oos-v14-new-tokens-zh",
}

# Shown above every table and chart on these pages, for the same reason it is
# shown on /results and /backtest: a performance figure has to carry its
# qualifier where it is read, not in the footer.
SIM_NOTICE = {
    "en": ("<strong>Simulated results &mdash; no real money.</strong> Every figure below is "
           "computed from historical price data by a backtest. No capital was invested and no "
           "orders were placed. Backtests apply a strategy to the past with full knowledge of how "
           "that period turned out, and the figures exclude slippage and liquidity effects, though a "
           "simulated 0.1% exchange fee is charged on every rebalance, DCA buy and redeployment. "
           "Simulated and past performance is <strong>not a reliable indicator of future "
           "results</strong>. AQMath is software, not investment advice."),
    "zh-Hans": ("<strong>模拟结果 &mdash; 未使用真实资金。</strong>以下每一项数据均由回测根据历史价格数据计算得出。"
                "未投入任何资金，也未下过任何订单。回测是在完全知晓该时段结果的前提下把策略套用于过去，"
                "且数据不包含滑点与流动性影响，但会对每次再平衡、DCA 买入和资金重新部署收取 0.1% 的模拟交易所手续费。"
                "模拟表现与过往表现<strong>不能可靠地预示未来结果</strong>。"
                "AQMath 是软件，不是投资建议。"),
}

UI = {
    "en": {
        "hubTitle": "Research &amp; Validation",
        "hubKicker": "Out-of-sample evidence",
        "hubIntro": ("Published test reports for the AQMath Deleverage Modulator. Each report is "
                     "generated verbatim from the source write-up in the engine repository, so the "
                     "figures here are the figures the test produced. The point of publishing them "
                     "is that a drawdown claim is only worth as much as the test behind it."),
        "backToHub": "&larr; All research",
        "alsoIn": "Also available in",
        "published": "Published",
    },
    "zh-Hans": {
        "hubTitle": "研究与验证",
        "hubKicker": "样本外证据",
        "hubIntro": "AQMath 去杠杆调节器的公开测试报告。",
        "backToHub": "&larr; 全部研究",
        "alsoIn": "其他语言版本",
        "published": "发布日期",
    },
}

DOCS = [
    {
        "src": "how-aqmath-works.md",
        "out": "how-aqmath-works.html",
        "path": "/research/how-aqmath-works",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-08-07",
        "title": "How AQMath Works: Signals, Frozen Weights and What You Execute - AQMath",
        "shortTitle": "How AQMath Works &mdash; Signals &amp; What You Execute",
        "description": ("The must-read user guide: AQMath produces signal-only trading guidance "
                        "from frozen KKT risk-parity weights (re-optimised every 180 days) and the "
                        "daily v14 Deleverage Shield - the user executes every trade manually, on "
                        "their own exchange account."),
        # User guide, not a performance study: no simulated-results notice.
        "sim_notice": False,
        "altLabel": "中文",
    },
    {
        "src": "how-aqmath-works.zh-CN.md",
        "out": "how-aqmath-works-zh.html",
        "path": "/research/how-aqmath-works-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-08-07",
        "title": "AQMath 工作原理：信号、冻结权重与你执行什么 - AQMath",
        "shortTitle": "AQMath 工作原理 &mdash; 信号与你执行什么",
        "description": ("必读用户指南：AQMath 仅产生信号型交易指引，基于冻结的 KKT 风险平价"
                        "权重（每 180 天再优化）与每日 v14 去杠杆防护盾 — 用户在自己的交易所"
                        "账户上手动执行每一笔交易。"),
        "sim_notice": False,
        "altLabel": "English",
    },
    {
        "src": "feed-sensitivity.md",
        "out": "feed-sensitivity.html",
        "path": "/research/feed-sensitivity",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-08-09",
        "title": "Three Price Feeds, One Strategy: Does the Signal Depend on Who Tells You the Price? - AQMath",
        "shortTitle": "Three Price Feeds, One Strategy &mdash; Feed Sensitivity",
        "description": ("The shield trusts one free-tier aggregator for every signal. Pulling the "
                        "same eight tokens from three independent feeds shows exchanges agreeing to "
                        "~0.1% while the aggregator prints 49 unfiltered one-day moves above 30% in a "
                        "year - 41 corroborated by no exchange. The v14 replay outcome barely moves, "
                        "but trade timing and the macro loop's volatility input do."),
        "altLabel": "中文",
    },
    {
        "src": "feed-sensitivity.zh-CN.md",
        "out": "feed-sensitivity-zh.html",
        "path": "/research/feed-sensitivity-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-08-09",
        "title": "三个价格源，一个策略：信号取决于谁告诉你价格吗？ - AQMath",
        "shortTitle": "三个价格源，一个策略 &mdash; 数据源敏感性",
        "description": ("防护盾的每个信号都依赖一个免费档聚合器。把同样 8 个代币从三个独立"
                        "价格源拉取：交易所之间分歧仅 ~0.1%，而聚合器一年打出 49 次未经过滤的"
                        "超 30% 单日波动 — 其中 41 次没有任何交易所佐证。v14 回放结果几乎不动，"
                        "但交易时机与宏观回路的波动率输入会动。"),
        "altLabel": "English",
    },
    {
        "src": "mc-risk.md",
        "out": "mc-risk.html",
        "path": "/research/mc-risk",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-08-07",
        "title": "Institutional Risk Report: Does v14's Edge Survive 3,000 Synthetic Histories? - AQMath",
        "shortTitle": "Institutional Risk Report &mdash; 3,000 Synthetic Histories",
        "description": ("Stationary block bootstrap, Deflated Sharpe, White's Reality Check and "
                        "CVaR on the production v14 wiring: the drawdown cut wins in 98.6-99.7% of "
                        "3,000 paired synthetic histories per basket and the one-month tail is ~40% "
                        "thinner everywhere - but excess return over buy & hold is statistically zero."),
        "altLabel": "中文",
    },
    {
        "src": "mc-risk.zh-CN.md",
        "out": "mc-risk-zh.html",
        "path": "/research/mc-risk-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-08-07",
        "title": "机构级风险报告：v14 的优势能否经受 3,000 段合成历史？ - AQMath",
        "shortTitle": "机构级风险报告 &mdash; 3,000 段合成历史",
        "description": ("对生产 v14 接线做平稳分块自助法、通缩夏普、White 现实检验与 CVaR："
                        "每个组合 3,000 段成对合成历史中 98.6-99.7% 的路径回撤削减为正，"
                        "一个月尾部处处薄约 40% — 但相对买入持有的超额收益在统计上为零。"),
        "altLabel": "English",
    },
    {
        "src": "graveyard.md",
        "out": "graveyard.html",
        "path": "/research/graveyard",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-08-07",
        "title": "Graveyard Gauntlet: Who Saves the Basket When Tokens Die? - AQMath",
        "shortTitle": "Graveyard Gauntlet &mdash; Who Saves the Basket When Tokens Die?",
        "description": ("A worst-case basket holding CEL, LUNC and FTT through their 2022 deaths: "
                        "the system draws down 18% vs 62% for buy & hold, and the honest attribution "
                        "shows the optimizer dodging slow deaths, the Shield absorbing fast ones, and "
                        "the liveness screen cleaning up afterwards - not before."),
        "altLabel": "中文",
    },
    {
        "src": "graveyard.zh-CN.md",
        "out": "graveyard-zh.html",
        "path": "/research/graveyard-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-08-07",
        "title": "墓地试炼：代币死亡时谁来拯救组合？ - AQMath",
        "shortTitle": "墓地试炼 &mdash; 代币死亡时谁来拯救组合？",
        "description": ("最坏情况组合持有 CEL、LUNC 与 FTT 度过其 2022 年死亡：系统回撤 18% "
                        "vs 买入持有 62%，诚实归因显示优化器避开缓慢死亡、防护盾吸收快速死亡、"
                        "活性筛查事后清理 — 而不是事前。"),
        "altLabel": "English",
    },
    {
        "src": "robustness.md",
        "out": "robustness.html",
        "path": "/research/robustness",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-08-07",
        "title": "Robustness: How Far Can Reality Deviate Before the Shield Breaks? - AQMath",
        "shortTitle": "Robustness &mdash; How Far Can Reality Deviate Before the Shield Breaks?",
        "description": ("129 walk-forward re-runs perturb every user-facing knob one at a time and "
                        "stress fees to 20x and execution to 2 days late: no cliff found - two knobs "
                        "are true plateaus, one is a clean protection dial, and the drawdown cut "
                        "survives late execution almost intact."),
        "altLabel": "中文",
    },
    {
        "src": "robustness.zh-CN.md",
        "out": "robustness-zh.html",
        "path": "/research/robustness-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-08-07",
        "title": "稳健性：现实偏离多远防护盾才会失效？ - AQMath",
        "shortTitle": "稳健性 &mdash; 现实偏离多远防护盾才会失效？",
        "description": ("129 次滚动前推重跑逐一扰动每个面向用户的旋钮，并把手续费压到 20 倍、"
                        "执行延迟 2 天：未发现断崖 — 两个旋钮是真正的高原，一个是干净的保护旋钮，"
                        "回撤削减在延迟执行下几乎完整保留。"),
        "altLabel": "English",
    },
    {
        "src": "regime-autopsy.md",
        "out": "regime-autopsy.html",
        "path": "/research/regime-autopsy",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-08-07",
        "title": "Regime Autopsy: Does the Shield Survive Its Worst Regimes? - AQMath",
        "shortTitle": "Regime Autopsy &mdash; Does the Shield Survive Its Worst Regimes?",
        "description": ("Six named crash regimes - May 2021, LUNA, FTX, Aug 2024, 2025-26 - sliced "
                        "post-hoc on frozen-weight walk-forward series, with the ADV-K2 liveness "
                        "screen active: 15 of 15 covered regime-basket combinations show a positive "
                        "out-of-sample drawdown cut, LUNA contagion held to 16.8% vs 44.1% Buy & Hold."),
        "altLabel": "中文",
    },
    {
        "src": "regime-autopsy.zh-CN.md",
        "out": "regime-autopsy-zh.html",
        "path": "/research/regime-autopsy-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-08-07",
        "title": "市场状态尸检：防护盾能否在最差的市场状态中存活？ - AQMath",
        "shortTitle": "市场状态尸检 &mdash; 防护盾能否在最差的市场状态中存活？",
        "description": ("六个已命名的崩盘市场状态 — 2021 年 5 月、LUNA、FTX、2024 年 8 月、"
                        "2025-26 — 在冻结权重滚动前推序列上做事后切片，ADV-K2 活性筛查开启："
                        "15/15 个被覆盖的市场状态-组合搭配显示出正的样本外回撤削减，"
                        "LUNA 传染被控制在 16.8% vs 买入持有 44.1%。"),
        "altLabel": "English",
    },
    {
        "src": "liveness-screen.md",
        "out": "liveness-screen.html",
        "path": "/research/liveness-screen",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-08-07",
        "title": "Liveness Screen: Fixing the Dead-Token Weight Flaw - AQMath",
        "shortTitle": "Liveness Screen &mdash; Fixing the Dead-Token Weight Flaw",
        "description": ("The KKT risk-parity loop can hand a dead token a real allocation, because a "
                        "collapsed chart looks low-vol: a Celsius-style zombie won a 24.7% frozen "
                        "weight in our stress basket. We reproduce the flaw, reject three naive "
                        "filters, and ship the ADV-K2 cap-zero screen — +8.5% final value, Sharpe "
                        "0.24 to 0.32, zero cost on live-token baskets."),
        "altLabel": "中文",
    },
    {
        "src": "liveness-screen.zh-CN.md",
        "out": "liveness-screen-zh.html",
        "path": "/research/liveness-screen-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-08-07",
        "title": "活性筛查：修复死代币权重缺陷 - AQMath",
        "shortTitle": "活性筛查 &mdash; 修复死代币权重缺陷",
        "description": ("KKT 风险平价回路可能把一个死代币赋予真实配置，因为崩塌后的图表看起来"
                        "低波动：一个 Celsius 式僵尸在我们的压力组合中赢得 24.7% 冻结权重。"
                        "我们复现该缺陷、否决三种朴素过滤器，并上线 ADV-K2 上限归零筛查 — "
                        "最终价值 +8.5%，Sharpe 从 0.24 升至 0.32，在存续代币组合上零成本。"),
        "altLabel": "English",
    },
    {
        "src": "baskets-v14-hist3.md",
        "out": "baskets-v14-hist3.html",
        "path": "/research/baskets-v14-hist3",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-08-05",
        "title": "Three-Basket Comparison: v14 Dual-Speed Engine - AQMath",
        "shortTitle": "Three-Basket Comparison &mdash; v14 KKT MACRO + Shield",
        "description": ("Walk-forward E2E comparison of three structurally different baskets "
                        "(majors+gold, veterans+gold, new-gen alts) on the shipped v14 stack: "
                        "shared-window max drawdown 9.8% vs 25.4% Buy & Hold; the Shield cut "
                        "drawdown 30-36 pp in every window."),
        "altLabel": "中文",
    },
    {
        "src": "baskets-v14-hist3.zh-CN.md",
        "out": "baskets-v14-hist3-zh.html",
        "path": "/research/baskets-v14-hist3-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-08-05",
        "title": "三组合对比：v14 双速引擎 - AQMath",
        "shortTitle": "三组合对比 &mdash; v14 KKT MACRO + 防护盾",
        "description": ("三个结构不同组合（主流币+黄金、老将+黄金、新生代山寨币）在已上线 "
                        "v14 栈上的滚动前推 E2E 对比：共同窗口最大回撤 9.8% vs 买入持有 25.4%；"
                        "防护盾在每个窗口都把回撤削减 30-36 个百分点。"),
        "altLabel": "English",
    },
    {
        "src": "e2e-tiaq.md",
        "out": "e2e-tiaq.html",
        "path": "/research/e2e-tiaq",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-08-03",
        "title": "E2E Study: TIA / QNT / XRP + PAXG Anchor - AQMath",
        "shortTitle": "E2E Study &mdash; TIA / QNT / XRP + PAXG Anchor",
        "description": ("Walk-forward E2E test of a candidate basket (TIA, QNT, XRP, PAXG) on the "
                        "live dual-speed stack: max drawdown 16.9% vs 24.6% Buy & Hold, beta 0.62; "
                        "the KKT optimizer zero-weighted TIA on every re-optimisation."),
        "altLabel": "中文",
    },
    {
        "src": "e2e-tiaq.zh-CN.md",
        "out": "e2e-tiaq-zh.html",
        "path": "/research/e2e-tiaq-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-08-03",
        "title": "E2E 研究：TIA / QNT / XRP + PAXG 锚 - AQMath",
        "shortTitle": "E2E 研究 &mdash; TIA / QNT / XRP + PAXG 锚",
        "description": ("候选组合（TIA、QNT、XRP、PAXG）在实盘双速栈上的滚动前推 E2E 测试："
                        "最大回撤 16.9% vs 买入持有 24.6%，beta 0.62；KKT 优化器在每次再优化中"
                        "都把 TIA 赋予零权重。"),
        "altLabel": "English",
    },
    {
        "src": "oos-v14-new-tokens.md",
        "out": "oos-v14-new-tokens.html",
        "path": "/research/oos-v14-new-tokens",
        "lang": "en",
        "htmlLang": "en",
        "published": "2026-07-17",
        "title": "OOS Validation: Deleverage v14.0 on Unseen Tokens - AQMath",
        "shortTitle": "OOS Validation &mdash; v14.0 on Unseen Tokens",
        "description": ("Out-of-sample test of the shipped AQMath Deleverage Modulator v14.0 on 16 "
                        "baskets of never-tuned tokens: median 54.3 pp drawdown cut, Calmar up "
                        "in 16/16."),
        "altLabel": "\u4e2d\u6587",
    },
    {
        "src": "oos-v14-new-tokens.zh-CN.md",
        "out": "oos-v14-new-tokens-zh.html",
        "path": "/research/oos-v14-new-tokens-zh",
        "lang": "zh-Hans",
        "htmlLang": "zh-CN",
        "published": "2026-07-17",
        "title": "\u6837\u672c\u5916\u9a8c\u8bc1\uff1av14.0 \u672a\u89c1\u4ee3\u5e01\u6d4b\u8bd5 - AQMath",
        "shortTitle": "\u6837\u672c\u5916\u9a8c\u8bc1 &mdash; v14.0 \u672a\u89c1\u4ee3\u5e01",
        "description": ("AQMath \u53bb\u6760\u6746\u8c03\u8282\u5668 v14.0 \u7684\u6837\u672c\u5916\u6d4b\u8bd5\uff1a"
                        "\u5728 16 \u4e2a\u4ece\u672a\u7528\u4e8e\u8c03\u53c2\u7684\u4ee3\u5e01\u7ec4\u5408\u4e0a\u9a8c\u8bc1\uff0c"
                        "\u6700\u5927\u56de\u64a4\u4e2d\u4f4d\u6570\u524a\u51cf 54.3 \u4e2a\u767e\u5206\u70b9\uff0c"
                        "Calmar \u5728 16/16 \u4e2a\u7ec4\u5408\u4e2d\u5168\u90e8\u63d0\u5347\uff0c"
                        "\u5e76\u5305\u542b\u6b7b\u4ea1\u4ee3\u5e01\u4e0e\u77ed\u5386\u53f2\u538b\u529b\u6848\u4f8b\u3002"),
        "altLabel": "English",
    },
]

# Language pairs that describe the same document, for hreflang.
TRANSLATION_SETS = [
    ["/research/oos-v14-new-tokens", "/research/oos-v14-new-tokens-zh"],
    ["/research/how-aqmath-works", "/research/how-aqmath-works-zh"],
    ["/research/feed-sensitivity", "/research/feed-sensitivity-zh"],
    ["/research/mc-risk", "/research/mc-risk-zh"],
    ["/research/graveyard", "/research/graveyard-zh"],
    ["/research/robustness", "/research/robustness-zh"],
    ["/research/regime-autopsy", "/research/regime-autopsy-zh"],
    ["/research/liveness-screen", "/research/liveness-screen-zh"],
    ["/research/baskets-v14-hist3", "/research/baskets-v14-hist3-zh"],
    ["/research/e2e-tiaq", "/research/e2e-tiaq-zh"],
]


# ---------------------------------------------------------------- markdown ---

CODE_RE = re.compile(r"`([^`]+)`")
IMG_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
BOLD_RE = re.compile(r"\*\*(.+?)\*\*")
ITALIC_RE = re.compile(r"\*([^*]+)\*")
TABLE_RULE_RE = re.compile(r"^\|[\s:|-]+\|$")


def rewrite_target(target):
    for old, new in REWRITE.items():
        if target.startswith(old):
            return new + target[len(old):]
        if target == old:
            return new
    return target


def svg_box(url):
    """Intrinsic width/height so the chart does not shift the page while loading."""
    path = ROOT / url.lstrip("/")
    if not path.exists():
        raise SystemExit(f"referenced asset missing: {url}")
    head = path.read_text(encoding="utf-8")[:400]
    w = re.search(r'\bwidth="(\d+)"', head)
    h = re.search(r'\bheight="(\d+)"', head)
    if not (w and h):
        raise SystemExit(f"cannot read intrinsic size of {url}")
    return w.group(1), h.group(1)


def inline(text):
    """Inline Markdown -> HTML. Escapes first, so source text can never inject markup."""
    codes = []

    def stash(m):
        codes.append(htmllib.escape(m.group(1)))
        return f"\x00{len(codes) - 1}\x00"

    text = CODE_RE.sub(stash, text)
    text = htmllib.escape(text)
    text = BOLD_RE.sub(r"<strong>\1</strong>", text)
    text = ITALIC_RE.sub(r"<em>\1</em>", text)
    text = LINK_RE.sub(
        lambda m: f'<a href="{rewrite_target(m.group(2))}">{m.group(1)}</a>', text)
    text = re.sub(r"\x00(\d+)\x00", lambda m: f"<code>{codes[int(m.group(1))]}</code>", text)
    return text


def render_table(rows):
    align_row = rows[1]
    aligns = []
    for cell in [c.strip() for c in align_row.strip("|").split("|")]:
        if cell.endswith(":") and cell.startswith(":"):
            aligns.append("center")
        elif cell.endswith(":"):
            aligns.append("right")
        else:
            aligns.append("left")

    def cells(row):
        return [c.strip() for c in row.strip().strip("|").split("|")]

    out = ['<div class="rs-tablewrap">', "<table>", "<thead><tr>"]
    for i, cell in enumerate(cells(rows[0])):
        a = aligns[i] if i < len(aligns) else "left"
        out.append(f'<th style="text-align:{a}">{inline(cell)}</th>')
    out.append("</tr></thead>")
    out.append("<tbody>")
    for row in rows[2:]:
        out.append("<tr>")
        for i, cell in enumerate(cells(row)):
            a = aligns[i] if i < len(aligns) else "left"
            out.append(f'<td style="text-align:{a}">{inline(cell)}</td>')
        out.append("</tr>")
    out.append("</tbody></table></div>")
    return "\n".join(out)


def render_paragraph(lines):
    if len(lines) > 1 and all(l.startswith("**") for l in lines):
        # A metadata block (Date:/Engine:/Status:) - one fact per line, as written.
        return "<p>" + "<br>\n".join(inline(l) for l in lines) + "</p>"
    return "<p>" + inline(" ".join(lines)) + "</p>"


def markdown_to_html(md):
    """Render the Markdown subset these reports actually use. Not a general parser:
    it fails loudly on anything it does not recognise rather than dropping it."""
    lines = md.replace("\r\n", "\n").split("\n")
    out = []
    para = []
    items = []
    i = 0

    def flush():
        if para:
            out.append(render_paragraph(list(para)))
            para.clear()
        if items:
            out.append("<ul>" + "".join(f"<li>{inline(x)}</li>" for x in items) + "</ul>")
            items.clear()

    while i < len(lines):
        raw = lines[i]
        line = raw.strip()

        if not line:
            flush()
            i += 1
            continue

        if line == "---":
            flush()
            out.append("<hr>")
            i += 1
            continue

        m = re.match(r"^(#{1,4})\s+(.*)$", line)
        if m:
            flush()
            lvl = len(m.group(1))
            out.append(f"<h{lvl}>{inline(m.group(2))}</h{lvl}>")
            i += 1
            continue

        if line.startswith("> "):
            flush()
            out.append(f"<blockquote>{inline(line[2:])}</blockquote>")
            i += 1
            continue

        m = IMG_RE.fullmatch(line)
        if m:
            flush()
            url = rewrite_target(m.group(2))
            w, h = svg_box(url)
            out.append(f'<figure class="rs-fig"><img src="{url}" alt="{htmllib.escape(m.group(1))}" '
                       f'width="{w}" height="{h}" loading="lazy" decoding="async"></figure>')
            i += 1
            continue

        if line.startswith("|"):
            flush()
            if i + 1 >= len(lines) or not TABLE_RULE_RE.match(lines[i + 1].strip()):
                raise SystemExit(f"table without an alignment row at line {i + 1}: {line}")
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append(lines[i].strip())
                i += 1
            out.append(render_table(rows))
            continue

        if line.startswith("- "):
            if para:
                flush()
            items.append(line[2:])
            i += 1
            continue

        if items and raw.startswith("  "):
            # Continuation of the previous list item.
            items[-1] = items[-1] + " " + line
            i += 1
            continue

        para.append(line)
        i += 1

    flush()
    return "\n".join(out)


# ------------------------------------------------------------------- pages ---

def asset_stamp():
    """Reuse whatever stamp tools/stamp_version.py last wrote, so these pages
    never point at a stylesheet version that does not exist."""
    body = (ROOT / "terms.html").read_text(encoding="utf-8")
    m = re.search(r'href="/styles\.min\.css\?v=([\w]+)"', body)
    if not m:
        raise SystemExit("cannot read current asset stamp from terms.html")
    return m.group(1)


def alternates(path):
    links = []
    for group in TRANSLATION_SETS:
        if path not in group:
            continue
        for other in group:
            doc = next(d for d in DOCS if d["path"] == other)
            links.append(f'<link rel="alternate" hreflang="{doc["lang"]}" '
                         f'href="{SITE}{other}">')
        links.append(f'<link rel="alternate" hreflang="x-default" href="{SITE}{group[0]}">')
    return links


def shell(lang, html_lang, title, description, path, body, extra_head=()):
    stamp = asset_stamp()
    head = "\n".join(list(extra_head) + alternates(path))
    return BANNER + f"""<!DOCTYPE html>
<html lang="{html_lang}">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<meta name="description" content="{description}">
<meta name="robots" content="index, follow">
<link rel="canonical" href="{SITE}{path}">
<link rel="icon" href="/favicon.ico">
<link rel="icon" type="image/png" sizes="512x512" href="/favicon.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<meta property="og:type" content="article">
<meta property="og:url" content="{SITE}{path}">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:site_name" content="AQMath">
<meta property="og:image" content="{SOCIAL_IMAGE}">
<meta property="og:image:secure_url" content="{SOCIAL_IMAGE}">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="{SOCIAL_IMAGE_ALT}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{description}">
<meta name="twitter:image" content="{SOCIAL_IMAGE}">
<meta name="twitter:image:alt" content="{SOCIAL_IMAGE_ALT}">
{head}
<!-- Fonts are self-hosted (see @font-face in styles.css) so no request reaches Google. -->
<link rel="preload" href="/fonts/plus-jakarta-sans-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="/styles.min.css?v={stamp}">
</head>
<body>

<main class="legal-page research-page">
    <a class="legal-page-brand" href="/">
        <div class="logo-box">AQ</div>
        <div>
            <div class="logo-name">AQMath</div>
            <div class="logo-tag">&larr; aqmath.xyz</div>
        </div>
    </a>

{body}
</main>

<footer class="site-footer">
    &copy; 2026 AQMath &mdash; Private. Non-Custodial.<br>
    <a href="/">Home</a><span class="sep">|</span><a href="/about">About</a><span class="sep">|</span><a href="/research/">Research</a><span class="sep">|</span><a href="/impressum">Impressum</a><span class="sep">|</span><a href="/privacy">Privacy</a><span class="sep">|</span><a href="/terms">Terms</a><span class="sep">|</span><a href="/widerruf">Widerruf</a>
</footer>

</body>
</html>
"""


def render_doc(doc):
    md = (SRC_DIR / doc["src"]).read_text(encoding="utf-8")
    ui = UI[doc["lang"]]
    other = next((d for d in DOCS
                  for g in TRANSLATION_SETS
                  if doc["path"] in g and d["path"] in g and d["path"] != doc["path"]), None)

    body_md = markdown_to_html(md)
    # The source's own cross-language line points at a repo file; the header link
    # below is the real one, so drop the duplicate.
    body_md = re.sub(r"<blockquote>.*?</blockquote>\s*", "", body_md, count=1, flags=re.S)

    nav = [f'<p class="rs-nav"><a href="/research/">{ui["backToHub"]}</a>']
    if other:
        nav.append(f'<span class="sep">|</span>{ui["alsoIn"]} '
                   f'<a href="{other["path"]}" hreflang="{other["lang"]}">{doc["altLabel"]}</a>')
    nav.append("</p>")

    # The document title has to be the first heading a reader and a crawler meet,
    # so lift it out of the rendered body and put the notices underneath it.
    m = re.match(r"\s*(<h1>.*?</h1>)\s*", body_md, flags=re.S)
    if not m:
        raise SystemExit(f"{doc['src']}: expected the document to open with a level-1 heading")
    heading, rest = m.group(1), body_md[m.end():]

    body = "\n".join([
        "".join(nav),
        heading,
        f'<p class="legal-updated">{ui["published"]}: {doc["published"]}</p>',
    ])
    # Documents without performance figures (e.g. the user guide) opt out of
    # the simulated-results notice via "sim_notice": False.
    if doc.get("sim_notice", True):
        body += f'\n<p class="sim-notice">{SIM_NOTICE[doc["lang"]]}</p>'
    body += "\n" + rest
    return shell(doc["lang"], doc["htmlLang"], doc["title"], doc["description"],
                 doc["path"], body)


def render_hub():
    ui = UI["en"]
    cards = []
    for doc in DOCS:
        if doc["lang"] != "en":
            continue
        other = next((d for d in DOCS
                      for g in TRANSLATION_SETS
                      if doc["path"] in g and d["path"] in g and d["path"] != doc["path"]), None)
        alt = (f' <span class="rs-card-alt">&middot; <a href="{other["path"]}" '
               f'hreflang="{other["lang"]}">{doc["altLabel"]}</a></span>') if other else ""
        cards.append(
            f'<li class="rs-card"><a href="{doc["path"]}">{doc["shortTitle"]}</a>'
            f'<span class="rs-card-date">{doc["published"]}</span>{alt}'
            f'<p>{doc["description"]}</p></li>')
    body = "\n".join([
        f'<div class="rs-kicker">{ui["hubKicker"]}</div>',
        f'<h1>{ui["hubTitle"]}</h1>',
        f'<p>{ui["hubIntro"]}</p>',
        '<ul class="rs-list">',
        *cards,
        "</ul>",
        '<p>Interactive version: run the same engine on your own price data at '
        '<a href="/backtest">/backtest</a>, or see the live paper-trading log at '
        '<a href="/results">/results</a>.</p>',
    ])
    # "/research" 301-redirects to "/research/" on Pages, so canonical/og:url and
    # the sitemap must use the trailing-slash form or crawlers log a redirect hop.
    return shell(
        "en", "en", "Research &amp; Validation &mdash; AQMath",
        "Published out-of-sample validation reports for the AQMath Deleverage Modulator: "
        "test methodology, per-basket results, stress cases and caveats.",
        "/research/", body)


def build():
    pages = {"index.html": render_hub()}
    for doc in DOCS:
        pages[doc["out"]] = render_doc(doc)
    return pages


def main(check_only=False):
    if not SRC_DIR.exists():
        raise SystemExit(f"missing source directory: {SRC_DIR}")
    pages = build()

    stale = []
    for name, text in pages.items():
        path = OUT_DIR / name
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            stale.append(name)

    if check_only:
        if stale:
            print("research pages STALE - re-run tools/build_research.py:")
            for n in stale:
                print("  research/" + n)
            return 1
        print(f"research pages OK - {len(pages)} in sync with _research/")
        return 0

    OUT_DIR.mkdir(exist_ok=True)
    for name, text in pages.items():
        (OUT_DIR / name).write_text(text, encoding="utf-8")
        h1 = len(re.findall(r"<h1\b", text))
        if h1 != 1:
            raise SystemExit(f"research/{name}: expected exactly 1 <h1>, found {h1}")
        print(f"  research/{name:28s} {len(text):>7,}B h1=1")
    print(f"wrote {len(pages)} research pages from {SRC_DIR.name}/")
    return 0


if __name__ == "__main__":
    sys.exit(main(check_only="--check" in sys.argv))
