"""Download the Google Fonts webfonts into /fonts so nothing is fetched from
Google at runtime.

Why: a dynamically embedded Google Font transmits the visitor's IP address to
Google (US) before any consent. LG Munchen I, 20.01.2022, Az. 3 O 17493/20
awarded damages for exactly that. Self-hosting removes the transfer entirely,
so no consent banner is needed for fonts — and it also drops two render
blocking third-party origins (fonts.googleapis.com, fonts.gstatic.com).

Both families are variable fonts, so each subset is a single woff2 covering the
whole weight range. Only `latin` and `latin-ext` are kept: the site ships EN and
zh-CN, and neither family contains CJK glyphs anyway (those fall back to system
fonts), so cyrillic/greek/vietnamese subsets would be dead weight.

Usage:  python tools/fetch_fonts.py
Re-run only when a font family or weight range changes. The generated
@font-face block is written to fonts/fonts.css for reference; the copy that is
actually served lives at the top of styles.css.
"""
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "fonts"

# Chrome UA is required — Google serves woff2 only to browsers that support it.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

FAMILIES = {
    "jetbrains-mono": "JetBrains+Mono:wght@300..700",
    "plus-jakarta-sans": "Plus+Jakarta+Sans:wght@300..800",
}

KEEP_SUBSETS = ("latin", "latin-ext")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def blocks(css):
    """Yield (subset_name, block_text) for every @font-face in the CSS."""
    # Google emits a `/* subset */` comment directly above each @font-face.
    for m in re.finditer(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S):
        yield m.group(1), m.group(2)


def build():
    OUT_DIR.mkdir(exist_ok=True)
    out_css = []
    for slug, spec in FAMILIES.items():
        css = get(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode()
        kept = 0
        for subset, block in blocks(css):
            if subset not in KEEP_SUBSETS:
                continue
            m = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", block)
            if not m:
                raise SystemExit(f"no woff2 url in {slug}/{subset}")
            fname = f"{slug}-{subset}.woff2"
            (OUT_DIR / fname).write_bytes(get(m.group(1)))
            out_css.append(block.replace(m.group(1), f"/fonts/{fname}"))
            print(f"  {fname:38} {(OUT_DIR / fname).stat().st_size:>7,} bytes")
            kept += 1
        if kept != len(KEEP_SUBSETS):
            raise SystemExit(f"{slug}: expected {len(KEEP_SUBSETS)} subsets, kept {kept}")

    header = ("/* Self-hosted webfonts — generated by tools/fetch_fonts.py.\n"
              "   Keep in sync with the copy at the top of styles.css. */\n")
    (OUT_DIR / "fonts.css").write_text(header + "\n".join(out_css) + "\n",
                                      encoding="utf-8")
    print(f"\nwrote {OUT_DIR / 'fonts.css'} — paste these rules at the top of styles.css")


if __name__ == "__main__":
    build()
